name = "Minecraft Extended"
author = "Wizard Dragon"
version = "0.7.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46851b81d0ad58aedbe8275c4502a47436d08bc1164e32f44db62314a2735685"

[versions]
minecraft = "1.19.2"
quilt = "0.18.8"

[options]
datapack-folder = "config/paxi/datapacks"
