name = "Minecraft Extended"
author = "Wizard Dragon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "738991f00a3d0bc664338164e6dc10c0da72ae4404d55c6c9065a7d2edf5cfa5"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1-beta.66"
