name = "Minecraft Extended"
author = "Wizard Dragon"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "418825389e4e005ba7d187b270c7d29f41414b90f202af600dff5fab3cbaec8b"

[versions]
minecraft = "1.19.2"
quilt = "0.18.2"
